# Generated by Django 6.0.4 on 2026-06-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(db_column='id_tipo_producto', primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True)),
                ('vencimiento_refrigerado', models.CharField(blank=True, max_length=100, null=True)),
                ('vencimiento_congelado', models.CharField(blank=True, max_length=100, null=True)),
                ('vencimiento_bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('vencimiento_toppinera', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Producto',
                'verbose_name_plural': 'Tipos de Producto',
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('fecha_elaboracion', models.DateField()),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('proveedor', models.TextField(blank=True, null=True)),
                ('id_tipo_producto', models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='Inventory.tipoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
