# Generated by Django 6.0.4 on 2026-09-11 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CondicionVencimiento',
            fields=[
                ('id_condicion', models.AutoField(db_column='id_condicion', primary_key=True, serialize=False)),
                ('metodo', models.CharField(max_length=20)),
                ('anotacion', models.CharField(blank=True, max_length=150, null=True)),
                ('duracion_valor', models.IntegerField(blank=True, null=True)),
                ('duracion_unidad', models.CharField(blank=True, max_length=10, null=True)),
                ('especial', models.CharField(blank=True, max_length=20, null=True)),
                ('id_tipo_producto', models.ForeignKey(db_column='id_tipo_producto', on_delete=django.db.models.deletion.CASCADE, to='Inventory.tipoproducto')),
            ],
            options={
                'verbose_name': 'Condicion de vencimiento',
                'verbose_name_plural': 'Condiciones de vencimiento',
                'db_table': 'condiciones_vencimiento',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_condicion',
            field=models.ForeignKey(blank=True, db_column='id_condicion', null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.condicionvencimiento'),
        ),
        migrations.CreateModel(
            name='Desperdicio',
            fields=[
                ('id_desperdicio', models.AutoField(db_column='id_desperdicio', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('costo_perdido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Inventory.producto')),
            ],
            options={
                'verbose_name': 'Desperdicio',
                'verbose_name_plural': 'Desperdicios',
                'db_table': 'desperdicio',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='id_venta', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='Inventory.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
    ]
